#config_version=4
mode:
  code: mpf.modes.high_score.code.high_score.HighScore
  priority: 500
  start_events: game_ending, start_high_score
  use_wait_queue: true

# Instructions on how to use this mode:
# http://docs.missionpinball.org/en/latest/game_logic/high_scores/index.html

high_score:
  award_slide_display_time: 4s
  categories:
  - score:
      - GRAND CHAMPION
      - HIGH SCORE 1
      - HIGH SCORE 2
      - HIGH SCORE 3
      - HIGH SCORE 4
  defaults:
    score:
      - BRI: 4242
      - GHK: 2323
      - JK: 1337
      - QC: 42
      - MPF: 23

slide_player:
  high_score_enter_initials: high_score_enter_initials
  high_score_award_display:
    high_score_award_display:
        action: play
    high_score_enter_initials:
        action: remove

slides:
  high_score_enter_initials:
  - type: text
    text: PLAYER (player_num)
    style: dmd_med
    anchor_y: bottom
    x: center-27
    y: bottom+21
  - type: text
    text: (award)
    style: dmd_small
    anchor_y: bottom
    x: center-27
    y: bottom+12
  - type: text_input
    key: high_score
    style: dmd_med
    anchor_y: bottom
    max_chars: 3
    y: 1
    animations:
      show_slide:
      - property: opacity
        value: 1
        duration: 0.3s
        easing: in_out_quint
      - property: opacity
        value: 0
        duration: 0.3s
        repeat: true
        easing: in_out_quint

  - type: text
    text: ""
    key: high_score
    anchor_x: left
    x: left+90
    style: dmd_big

  high_score_award_display:
  - type: text
    text: (player_name)
    color: ffffff
    style: dmd_big
    anchor_y: middle
    anchor_x: middle
    x: middle
    y: middle
  - type: text
    text: (award)
    color: ffffff
    style: dmd_med
    anchor_y: top
    anchor_x: middle
    y: top-1
    x: middle
  - type: text
    text: (value)
    color: ffffff
    number_grouping: true
    style: dmd_med
    anchor_y: bottom
    anchor_x: middle
    y: bottom+1
    x: middle
