#config_version=4
mode:
  code: mpf.modes.service.code.service.Service
  priority: 100000
  game_mode: False
  start_events: reset_complete
  stop_events: shutdown
  stop_on_ball_end: False

event_player:
    # adjust this to change the tags
    sw_service_door_open_active:
        - service_door_opened
    sw_service_door_open_inactive:
        - service_door_closed
    sw_service_door_closed_active:
        - service_door_closed
    sw_service_door_closed_inactive:
        - service_door_opened
    sw_power_off_inactive:
        - service_power_on
    sw_power_off_active:
        - service_power_off
    sw_power_on_inactive:
        - service_power_off
    sw_power_on_active:
        - service_power_on

sounds:
  power_off:
    track: sfx
  switch_hit:
    track: sfx

sound_player:
    service_power_off: power_off
    service_switch_hit: switch_hit

slide_player:
  # doof open
  service_door_opened:
    service_door_open:
      action: play
  service_door_closed:
    service_door_open:
      action: remove

  # menu
  service_menu_show:
    service_menu:
      action: play
      priority: 1
  service_menu_hide:
    service_menu:
      action: remove

  # switch test
  service_switch_test_start:
    service_switch_test:
      action: play
      priority: 2
  service_switch_test_stop:
    service_switch_test:
      action: remove

  # coil test:
  service_coil_test_start:
    service_coil_test:
      action: play
      priority: 2
  service_coil_test_stop:
    service_coil_test:
      action: remove

  # settings:
  service_settings_start:
    service_settings:
      action: play
      priority: 2
  service_settings_stop:
    service_settings:
      action: remove

widget_player:
  # power off
  service_power_off:
    service_power_off_door_open:
      action: add
      slide: service_door_open
    service_power_off_coil_test:
      action: add
      slide: service_coil_test
  service_power_on:
    service_power_off_door_open:
      action: remove
      slide: service_door_open
    service_power_off_coil_test:
      action: remove
      slide: service_coil_test

  # menu items
  service_menu_deselected:
    service_menu_item_switch:
      action: remove
      slide: service_menu
    service_menu_item_coil:
      action: remove
      slide: service_menu
    service_menu_item_settings:
      action: remove
      slide: service_menu
  service_menu_selected_switch:
    service_menu_item_switch:
      action: add
      slide: service_menu
  service_menu_selected_coil:
    service_menu_item_coil:
      action: add
      slide: service_menu
  service_menu_selected_settings:
    service_menu_item_settings:
      action: add
      slide: service_menu


slides:
  # door open
  service_door_open:
  - type: text
    text: Door Open
    style: medium
    anchor_y: bottom
    x: center
    y: bottom+21
  - type: text
    text: Press enter for service
    style: small
    anchor_y: bottom
    x: center
    y: bottom+12
  # menu
  service_menu:
  - type: text
    text: Service Menu
    style: small
    anchor_y: top
    x: center
    y: top
  # switch test
  service_switch_test:
  - type: text
    text: Switch Test
    style: small
    anchor_y: top
    x: center
    y: top
  - type: text
    text: "Last: (switch_num)"
    style: small
    y: center+6
  - type: text
    text: "(switch_name)"
    style: small
    y: center
  - type: text
    text: "(switch_label)"
    style: small
    y: center-6
  - type: text
    text: (switch_state)
    style: small
    anchor_y: bottom
    y: bottom
  # coil test
  service_coil_test:
  - type: text
    text: "Coil Test - (board_name)"
    style: small
    anchor_y: top
    x: center
    y: top
  - type: text
    text: "(coil_name)"
    style: small
    y: center+6
  - type: text
    text: "(coil_label)"
    style: small
    y: center
  - type: text
    text: "(coil_num)"
    style: small
    y: center-6
  # settings
  service_settings:
  - type: text
    text: "Settings"
    style: small
    anchor_y: top
    x: center
    y: top
  - type: text
    text: "(settings_label)"
    style: small
    y: center+6
  - type: text
    text: "(value_label)"
    style: small
    y: center

widgets:
  # power off on door open slide
  service_power_off_door_open:
    type: text
    text: Coil Power Off
    anchor_y: bottom
    x: center
    y: bottom+4
    style: medium
    animations:
      add_to_slide:
      - property: opacity
        value: 1
        duration: 0.5s
      - property: opacity
        value: 0
        duration: 0.5s
        repeat: true
  # power off on coil test slide
  service_power_off_coil_test:
    type: text
    text: Coil Power Off
    style: small
    anchor_y: bottom
    y: bottom-2
    animations:
      add_to_slide:
      - property: opacity
        value: 1
        duration: 0.5s
      - property: opacity
        value: 0
        duration: 0.5s
        repeat: true


  # menu items
  service_menu_item_switch:
    type: text
    text: Switch Test
    anchor_y: center
    style: medium
  service_menu_item_coil:
    type: text
    text: Coil Test
    anchor_y: center
    style: medium
  service_menu_item_settings:
    type: text
    text: Settings
    anchor_y: center
    style: medium